<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f28e52f8-4339-490d-8cff-53a45f797d99</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MusicPlatform\MusicPlatform.csproj" />
	</ItemGroup>


</Project>
