@MusicPlatform.WebApi_HostAddress = http://localhost:5193

GET {{MusicPlatform.WebApi_HostAddress}}/
Accept: application/json

###
POST http://localhost:5193/api/songs
Content-Type: application/json

{
  "title": "API Test Song",
  "mainArtist": "API Test Artist",
  "featuredArtists": [
    "Featured Artist"
  ],
  "albums": [
    {
      "title": "API Test Album",
      "releaseDate": "2026-09-30"
    }
  ],
  "media": [
    {
      "type": "YouTube",
      "externalId": "test-video-id"
    }
  ]
}

###
GET http://localhost:5193/api/songs/47

### get all songs
GET http://localhost:5193/api/songs
Accept: application/json

### search for "api"
GET http://localhost:5193/api/songs/search?term=API
Accept: application/json

### Update song title
PUT http://localhost:5193/api/songs/47
Content-Type: application/json

"Updated API Test Song"


### Get updated song
GET http://localhost:5193/api/songs/47


### Delete song
DELETE http://localhost:5193/api/songs/47

### Get all artists
GET http://localhost:5193/api/tables/Artist
Accept: application/json

###

### Create artist
POST http://localhost:5193/api/tables/Artist/rows
Content-Type: application/json

{
  "values": {
    "Name": "API Test Artist"
  }
}

###

### Update artist
PUT http://localhost:5193/api/tables/Artist/rows/25
Content-Type: application/json

{
  "values": {
    "Name": "Updated API Test Artist"
  }
}

###

### Delete artist
DELETE http://localhost:5193/api/tables/Artist/rows/25

###

### Get all artists after CRUD test
GET http://localhost:5193/api/tables/Artist
Accept: application/json


### create artist
POST http://localhost:5193/api/tables/Artist/rows
Content-Type: application/json

{
  "values": {
    "name": "Test Artist"
  }
}

### update artist
PUT http://localhost:5193/api/tables/Artist/rows/26
Content-Type: application/json

{
  "values": {
    "name": "Updated API Test Artist"
  }
}

### delete artist
DELETE http://localhost:5193/api/tables/Artist/rows/26

###
GET http://localhost:5193/api/songs/search?term=teddy
